# Generated by Django 2.2.3 on 2019-11-11 13:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('mainapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExportHistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('out_file_path', models.TextField(default=None, null=True, verbose_name='Путь выгрузки отчёта')),
                ('catch_time', models.DateTimeField(default=None, null=True, verbose_name='Дата и время построения отчёта')),
                ('results_id', models.ManyToManyField(related_name='results_ids', to='mainapp.ParsingResults', verbose_name='ID результатов')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_id', to=settings.AUTH_USER_MODEL, verbose_name='ID пользователя')),
            ],
            options={
                'verbose_name': 'Таблица экспорта',
                'verbose_name_plural': 'Таблица экспорта',
            },
        ),
    ]
