# Generated by Django 2.2.5 on 2019-10-14 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('mainapp', '0008_delete_parsingsettings'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExportHistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('out_file_path', models.TextField(verbose_name='Путь выгрузки отчёта')),
                ('results_id', models.ManyToManyField(related_name='results_ids', to='mainapp.ParsingResults', verbose_name='ID результатов')),
            ],
            options={
                'verbose_name': 'Таблица экспорта',
                'verbose_name_plural': 'Таблица экспорта',
            },
        ),
    ]
