# Generated by Django 2.2.5 on 2019-10-14 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exportapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='exporthistory',
            name='catch_time',
            field=models.DateTimeField(default=None, null=True, verbose_name='Дата и время построения отчёта'),
        ),
    ]
