# Generated by Django 2.2.5 on 2019-10-16 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exportapp', '0002_exporthistory_catch_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exporthistory',
            name='out_file_path',
            field=models.TextField(default=None, null=True, verbose_name='Путь выгрузки отчёта'),
        ),
    ]
