# Generated by Django 2.2.5 on 2019-10-21 15:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ParsingTasks',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('link', models.TextField(verbose_name='Ссылка')),
                ('activate', models.BooleanField(default=True, verbose_name='Активно?')),
                ('update_time', models.IntegerField(default=24, verbose_name='Время обновления(в часах)')),
                ('task_user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='task_user_id', to=settings.AUTH_USER_MODEL, verbose_name='ID пользователя')),
            ],
            options={
                'verbose_name': 'Задача для парсинга',
                'verbose_name_plural': 'Задачи для парсинга',
            },
        ),
        migrations.CreateModel(
            name='ParsingResults',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.IntegerField(verbose_name='Код статуса')),
                ('json', models.TextField(default='', verbose_name='JSON')),
                ('datetime', models.DateTimeField(auto_now_add=True, verbose_name='Дата и время')),
                ('task_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='task_id', to='mainapp.ParsingTasks', verbose_name='ID задания')),
            ],
            options={
                'verbose_name': 'Результаты парсинга',
                'verbose_name_plural': 'Результаты парсинга',
            },
        ),
    ]
