# Generated by Django 2.2.5 on 2019-10-03 16:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='parsingtasks',
            name='activate',
            field=models.BooleanField(default=True, verbose_name='Активно?'),
        ),
        migrations.AddField(
            model_name='parsingtasks',
            name='update_time',
            field=models.IntegerField(default=24, verbose_name='Время обновления(в часах)'),
        ),
        migrations.CreateModel(
            name='ParsingResults',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.IntegerField(verbose_name='Код статуса')),
                ('datetime', models.DateTimeField(auto_now_add=True, verbose_name='Дата и время')),
                ('task_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.ParsingTasks', verbose_name='ID задания')),
            ],
            options={
                'verbose_name': 'Результаты парсинга',
                'verbose_name_plural': 'Результаты парсинга',
            },
        ),
    ]
