<<<<<<< HEAD
# Generated by Django 2.2.5 on 2019-10-04 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0002_auto_20191003_1935'),
    ]

    operations = [
        migrations.AddField(
            model_name='parsingresults',
            name='json',
            field=models.TextField(default='', verbose_name='JSON'),
        ),
    ]
=======
# Generated by Django 2.2.5 on 2019-10-04 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0002_auto_20191003_1935'),
    ]

    operations = [
        migrations.AddField(
            model_name='parsingresults',
            name='json',
            field=models.TextField(default='', verbose_name='JSON'),
        ),
    ]
>>>>>>> 6092c2cc49030bd16f0eb20e94a56d4a3ec29363
