# Generated by Django 2.2.5 on 2019-10-09 17:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0003_parsingresults_json'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parsingresults',
            name='task_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='task_id', to='mainapp.ParsingTasks', verbose_name='ID задания'),
        ),
    ]
