# Generated by Django 2.2.5 on 2019-10-11 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0006_auto_20191011_2013'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parsingsettings',
            name='finish_iteration_time',
            field=models.DateTimeField(default=None, null=True, verbose_name='Дата и время окончания итерации'),
        ),
        migrations.AlterField(
            model_name='parsingsettings',
            name='last_ping_time',
            field=models.DateTimeField(default=None, null=True, verbose_name='Дата и время окончания итерации'),
        ),
        migrations.AlterField(
            model_name='parsingsettings',
            name='start_iteration_time',
            field=models.DateTimeField(default=None, null=True, verbose_name='Дата и время начала итерации'),
        ),
    ]
