# Generated by Django 2.2.5 on 2019-10-12 16:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0007_auto_20191011_2015'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ParsingSettings',
        ),
    ]
